listen = "[::1]:6060"

[[sites]]

# URL Format: /{site}/{branch}/sysupgrade/

latest-version = "1.3"
# site name, used for the URL
name = "wetter"
# branch name, used for the url. Magic value `any` makes the update manager ignore the branch provided by the client
branch = "stable"
# A URL where to download the meshviewer.json output which is used by the map
meshinfo = "http://map.ff-en.de/data/wtt/meshviewer.json"
# A host that is scheduled for update will be redirected here
on-update = "/wetter/2020/sysupgrade"
# A host that is not scheduled for update will be redirected here
on-noupdate = "/wetter/2019/sysupgrade"
# If true, nodes which are unknown to the map will be updated
update-default = false

# If enabled, all hosts will be sent to the noupdate url. However the software will log if an
# update would have happened
dry-run = true

# If enabled, a router which has autoupdate disabled will be treated as having latest firmware
ignore-autoupdate-off = true
# How often should the data from the map be refreshed
refresh-interval = 60
# After a certain time of being offline after receiving an update a node is considered successfully updated.
# This is the setting for that time in seconds
update-timeout = 900

# After how many failed update attempts (router came back with an old version even though it received the update
broken-threshold = 3
# Storage file for persistent state of the update manager
state-file = "/var/lib/gluon-update-manager/wetter.json"
